import solanaConfig from '@solana-config/oxc/oxfmt';
import { defineConfig } from 'oxfmt';

export default defineConfig({
    ...solanaConfig,
    ignorePatterns: [
        // Build outputs (also gitignored).
        '**/dist/',
        '**/lib/',
        // The Next.js app under `web/` has its own format setup.
        'web/',
        // Generated by the recorder and snapshot tests — keep byte-stable.
        // Glob is `**/` so it matches both legacy layouts and the per-package layout.
        '**/__tests__/fixtures/',
        '**/__tests__/**/__snapshots__/',
    ],
});
